# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x05movie\" \n\x0cMovieRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\"J\n\nMovieReply\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05genre\x18\x04 \x01(\t2B\n\x0cMovieService\x12\x32\n\x08GetMovie\x12\x13.movie.MovieRequest\x1a\x11.movie.MovieReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIEREQUEST']._serialized_start=22
  _globals['_MOVIEREQUEST']._serialized_end=54
  _globals['_MOVIEREPLY']._serialized_start=56
  _globals['_MOVIEREPLY']._serialized_end=130
  _globals['_MOVIESERVICE']._serialized_start=132
  _globals['_MOVIESERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
